import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// / -> page.tsx
/**
 * This is the shared layout for all the routes
 * @param param0 
 * @returns 
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-3xl mb-40 flex flex-col md:flex-row lg:mx-auto`}>
        <div className="flex-auto min-w-0 flex flex-col">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
